### ISSUE TITLE
'npm exec p5-ts-types' and 'npm exec p5-ts-setup' says "'bash' is not recognized..." on Visual Studio Code

### ISSUE THREAD

**Issue by SpringySpring04** [benfc1993/p5-typescript#33]
This issue occurs on Windows 11 with Visual Studio Code and npm installed.

To reproduce this issue:

1. Open an empty (new) folder in Visual Studio Code
2. Open terminal, type `npm i p5-typescript`, wait for install
3. After finished, type `npm exec p5-ts-types` or `p5-ts-setup`
4. Resulting output is `'"bash"' is not recognized as an internal or external command, operable program or batch file.`

Things I have tried to resolve it:
- Restarting Visual Studio Code
- Trying again in another folder

Is there something I have to install on my system, considering "bash" is mentioned, or is there some better way around this?

**Comment by SpringySpring04** [comment]
UPDATE:
I have Git Bash installed on my system, and was able to get these scripts to run using Git Bash.

1. Add Git Bash to PATH by navigating to its install location, copying the address, and pasting it in the system environment PATH variable (System Properties > Advanced > Environment Variables... > System Variables > "Path")
2. Navigate to project folder containing the p5-typescript project after running `npm i p5-typescript` and run the following command using git bash: `git-bash ./node_modules/p5-typescript/bin/setup`

It at least worked for me but it's a strange workaround, and I can't seem to configure npm or yarn to use `git-bash` instead of trying to use `bash` which I don't have installed on my system nor do I want to install because I read that Windows Subsystem for Linux would take up a lot of space on my hard drive

**Comment by benfc1993** [comment]
I'll take a look into this, I suspect the shebang in the bin files is incorrect
